databases:
  - name: expenses_pro
    databaseName: expenses_pro
    user: expenses_pro_user

services:
  - type: web
    name: expenses-tracker
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expenses_pro
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false