databases:
  - name: expenses
    databaseName: expenses
    user: expenses_kloa_user

services:
  - type: web
    name: expense-tracker
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expenses
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false